name: test
GPU_ID: [0]
phase: test
patch_size: 1
random_count: 20
random_size: 20
data_process_type: [resize, resize] # None   crop   resize
img_size_c: [512, 512, 3]
img_size_s: [512, 512, 3]
alpha_tradeoff: [0.8, 0.85, 0.9, 0.95, 1.0]
ablationType: None

checkpoint_dir: None

vgg_weights: ./models/vgg_normalised.t7

data: # Directory of input images
  dir_content: ./example/content
  dir_style: ./example/content

dir_out: ../output # Root directory for saving results
output: # Subdirectories for saving results
  dir_result: results

batch_size: 1
