name: ccnet
GPU_ID: [0]
batch_size: 4
lr: 0.0001
lr_decay: 0.00005
lr_scale: 1.0
phase: train
ablationType: None

epoch: 2
iteration: 100000
img_size: [256,256,3] # Size of input image clipping
patch_size: 1

weight:
  content: 0.0
  style: 0.0
  cc: 300.0
  cc_comp: 15.0
  cc_cons: 1.0

dir_checkpoint: None
vgg_weights: ./models/ETNet/vgg_normalised.t7
data: # Directory of input images
  dir_content: ./data/coco_train
  dir_style: ./data/art

dir_out: ./output/train/CCNet # Root directory for saving results


output: # Subdirectories for saving results
  dir_log: logs
  dir_config: configs
  dir_sample: samples
  dir_checkpoint: checkpoints

freq_print: 200 # Frequence of printing synthesis images
freq_save: 200 # Frequence of saving models
freq_log: 20 # Frequence of saving log files


